
version: '3'
services:
# For dev, it's working!
  front:
    image: node:8.9.4
    container_name: "videosite-front"
 #   depends_on: 
 #     - backend
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run dev"
    working_dir: /src
    volumes:
      - "./front:/src"
    environment:
      - ROOT_API=localhost:3003
      - TESTI=TESTI_LASSI

 # backend:
 #   image: node:8.9.4
 #   container_name: "videosite-backend"
 #   ports:
 #     - 3002:3002
 #   command: bash -c "npm install && npm run watch"
 #   working_dir: /src
 #   volumes:
 #     - "./backend:/src"
 #   environment:
 #     HOST: 0.0.0.0
 #     MONGODB_URI: mongodb://localhost:27017
      #- SET_CONTAINER_TIMEZONE=true
      #- CONTAINER_TIMEZONE=Europe/Helsinki