
version: '3'
services:
# For dev, it's working!
  front:
    image: node:8.9.4
    container_name: "videosite-front"
    depends_on: 
      - backend
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run dev"
    working_dir: /src
    volumes:
      - "./front:/src"
    environment:
      - TESTI=http://testi
      - HOST=0.0.0.0
      - ROOT_API=localhost:3002

  backend:
    image: node:8.9.4
    container_name: "videosite-backend"
    depends_on: 
      - mongo
      - mongo-express
    ports:
      - 3002:3002
    command: bash -c "npm install && npm run watch"
    working_dir: /src
    volumes:
      - "./backend:/src"
    environment:
      HOST: 0.0.0.0
      MONGODB_URI: mongodb://mongo/test
      #- SET_CONTAINER_TIMEZONE=true
      #- CONTAINER_TIMEZONE=Europe/Helsinki

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
     # MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: 123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
   # environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: 123