version: '3.2'
services:
# For prod!
  app:
    image: videosite:latest
    container_name: "videosite"
    ports:
      - 3002:3002
    environment:
      HOST: 0.0.0.0
      MONGODB_URI: mongodb://mongo
      NODE_ENV: development
      ROOT_API: localhost:3003

  mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD: 123

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
    # environment:
      #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #  ME_CONFIG_MONGODB_ADMINPASSWORD: 123