version: '3.2'
services:
  front:
    image: lasa/videosite:front
    container_name: "videosite-front"
    depends_on: 
      - backend
    ports:
      - 80:8080
    environment:
      HOST: 0.0.0.0
      ROOT_API: localhost:3002

  backend:
    image: lasa/videosite:backend
    container_name: "videosite-backend"
    depends_on: 
      - mongo
      - mongo-express
    ports:
      - 3002:3002

    environment:
      HOST: 0.0.0.0
      MONGODB_URI: mongodb://mongo/

  mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081